version: "2"
services:
  db:
    image: mongo
    command: --nojournal --smallfiles --replSet rs0
    volumes:
      - "/data/db:/data/db"
    ports:
      - "27017:27017"
  web:
    image: ctags-web/web
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - $PWD:/ctags-web
    working_dir: /ctags-web
    command: bash ./scripts/run_web.sh
    ports:
      - "8080:8080"
    depends_on:
      - db
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.2
    environment:
      # - "discovery.type=single-node"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - db
